# Generated by Django 5.0.1 on 2024-03-16 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogupper',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(default='default_slug', max_length=50)),
                ('mainimage', models.ImageField(default='upload-image', upload_to='myapp/images')),
                ('location', models.CharField(max_length=30)),
                ('datee', models.TextField()),
                ('paragraphone', models.TextField()),
                ('imgone', models.ImageField(default='upload-image-one', upload_to='myapp/images')),
                ('imgtwo', models.ImageField(default='upload-image-two', upload_to='myapp/images')),
                ('imgthree', models.ImageField(default='upload-image-three', upload_to='myapp/images')),
                ('imgfour', models.ImageField(default='upload-image-four', upload_to='myapp/images')),
                ('paragraphtwo', models.TextField()),
                ('imgfive', models.ImageField(default='upload-image-five', upload_to='myapp/images')),
                ('imgsix', models.ImageField(default='upload-image-six', upload_to='myapp/images')),
                ('imgseven', models.ImageField(default='upload-image-seven', upload_to='myapp/images')),
                ('imgeight', models.ImageField(default='upload-image-eight', upload_to='myapp/images')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('content', models.TextField()),
                ('timeStap', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
